# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 123b96368b0e06d37834ca0911417481a3574bc7fd628ec4cb66fcad197cb26561d32b69695642e13c00df91fd41166530c5a3d086ccc93fd1415eb1fc954b29

test:
  secret_key_base: f279c3224fca8926c5d8d86ee13fe082c02152e09583ed62a33ebd1dd1e9e7984d2a3e5e1e439dfbc0f8f4f191a00fa85720529fb2ba0cf0333b518403b85f70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
